---
title: "Wraping around ggplot2"
author: "Elio Campitelli"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(ggperiodic)
library(ggplot2)
x <- seq(0, 360 - 10, by = 10)*pi/180
y <- seq(-90, 90, by = 10)*pi/180

Z <- expand.grid(x = x, y = y)
Z$z <- with(Z, 1.2*sin(x)*0.4*sin(y*2) - 
               0.5*cos(2*x)*0.5*sin(3*y) + 
               0.2*sin(4*x)*0.45*cos(2*x))
Z$x <- Z$x*180/pi
Z$y <- Z$y*180/pi

Z <- periodic(Z, x = c(0, 360))

ggplot(Z) +
  geom_contour(aes(x, y, z = z)) +
  coord_polar()
```


```{r}
map <- map_data("world")

ggplot(Z, aes(x, y), x = c(-180, 180)) +
  geom_contour(aes(z = z)) +
  geom_path(data = map, aes(long, lat, group = group))
```


```{r}
map <- periodic(map, long = long)

ggplot(Z, aes(x, y)) +
  geom_contour(aes(z = z)) +
  geom_path(data = map, aes(long, lat, group = group), long = c(0, 360))
```

